### ISSUE TITLE
Error with TransformerWrapper

### ISSUE THREAD

**Issue by pfeatherstone** [lucidrains/x-transformers#109]
```
model = TransformerWrapper(
    num_tokens  = 16,
    max_seq_len = 1024,
    attn_layers = Encoder(
        dim = 512,
        depth = 12,
        heads = 8
    )
)
x    = torch.randint(0, 256, (1, 1024))
mask = torch.ones_like(x).bool()
y    = model(x, mask = mask)
```

The above fails with error:
```
Traceback (most recent call last):
  File "xtransformers.py", line 25, in <module>
    y    = model(x, mask = mask)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/pf/.local/lib/python3.6/site-packages/x_transformers/x_transformers.py", line 1170, in forward
    x = self.token_emb(x) + pos_emb
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/pf/.local/lib/python3.6/site-packages/x_transformers/x_transformers.py", line 140, in forward
    token_emb = self.emb(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/sparse.py", line 158, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 1916, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self
```
Are there constraints on what `num_tokens` can be?

**Comment by lucidrains** [comment]
@pfeatherstone yup, in your case, `num_tokens = 256`

**Comment by pfeatherstone** [comment]
thanks

**Comment by pfeatherstone** [comment]
@lucidrains Sorry to bother again. I'm looking for a pair of models, encoder and decoder. 
The encoder should have inputs:
- data with dtype torch.uint8 and shape [B,N] 
- mask with dtype torch.bool and shape [B,N]
and have outputs:
- data with dtype torch.float32 and shape [B,N,C] where C is some number of channels

The decoder should have inputs:
- data with dtype torch.float32 and shape [B,N,C]
- mask with dtype torch.bool and shape [B,N]
Outputs:
- data with dtype torch.uint8 and shape [B,N]  

Can you recommend some suitable transformers?
