### ISSUE TITLE
Potential bug in `model.generate` 

### ISSUE THREAD

**Issue by guillaumeguy** [lucidrains/x-transformers#271]
hi there:

I was playing with the [toy_tasks](https://github.com/lucidrains/x-transformers/tree/main/examples/toy_tasks) example and it looks like the `model.generate` code doesn't work for decoding sequence shorter than encoding sequences.

Reproducible example:
https://gist.github.com/guillaumeguy/dd8993a622663db39aa1c54be9a875fd

Error: 
```
Traceback (most recent call last):
  File "/home/guillaume_guy/repos/pytorch-seq2seq/example.py", line 75, in <module>
    sample = model.generate(src, start_tokens, ENC_SEQ_LEN, mask = src_mask)
  File "/home/guillaume_guy/.conda/envs/user/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/guillaume_guy/.conda/envs/user/lib/python3.10/site-packages/x_transformers/x_transformers.py", line 2340, in generate
    return self.decoder.generate(seq_out_start, seq_len, context = encodings, context_mask = mask, **kwargs)
  File "/home/guillaume_guy/.conda/envs/user/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/guillaume_guy/.conda/envs/user/lib/python3.10/site-packages/x_transformers/autoregressive_wrapper.py", line 32, in inner
    out = fn(self, *args, **kwargs)
  File "/home/guillaume_guy/.conda/envs/user/lib/python3.10/site-packages/x_transformers/autoregressive_wrapper.py", line 231, in generate
    logits, new_cache = self.net(
  File "/home/guillaume_guy/.conda/envs/user/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/guillaume_guy/.conda/envs/user/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/guillaume_guy/.conda/envs/user/lib/python3.10/site-packages/x_transformers/x_transformers.py", line 2217, in forward
    x, intermediates = self.attn_layers(x, mask = mask, mems = mems, mem_masks = mem_masks, cache = cache, return_hiddens = True, seq_start_pos = seq_start_pos, **kwargs)
  File "/home/guillaume_guy/.conda/envs/user/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/guillaume_guy/.conda/envs/user/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/guillaume_guy/.conda/envs/user/lib/python3.10/site-packages/x_transformers/x_transformers.py", line 1786, in forward
    out, inter = block(x, context = context, mask = mask, context_mask = context_mask, prev_attn = prev_cross_attn, cache = next(iter_attn_cache, None), return_intermediates = True)
  File "/home/guillaume_guy/.conda/envs/user/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/guillaume_guy/.conda/envs/user/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/guillaume_guy/.conda/envs/user/lib/python3.10/site-packages/x_transformers/x_transformers.py", line 1216, in forward
    out, intermediates = self.attend(
  File "/home/guillaume_guy/.conda/envs/user/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/guillaume_guy/.conda/envs/user/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/guillaume_guy/.conda/envs/user/lib/python3.10/site-packages/x_transformers/attend.py", line 349, in forward
    sim = sim.masked_fill(~mask, mask_value)
RuntimeError: The size of tensor a (258) must match the size of tensor b (230) at non-singleton dimension 3

```

**Comment by guillaumeguy** [comment]
The trick that I found was to:

in the model constructor, pass ` dec_max_seq_len = ENC_SEQ_LEN + 1` and, in `model.generate` , pass `seq_len=DEC_SEQ_LEN`. That will work

**Comment by lucidrains** [comment]
@guillaumeguy hey Guillaume! thanks for reporting this!

could you try the latest version and see if it resolves it on your end?

**Comment by guillaumeguy** [comment]
Now I'm getting this error (same example):
```  the network cannot use cached key values when decoding outside the max sequence length. most likely because you are using absolute positional embedding. you can switch to rotary embeddings to resolve this issue'
AssertionError: the network cannot use cached key values when decoding outside the max sequence length. most likely because you are using absolute positional embedding. you can switch to rotary embeddings to resolve this issue```. 



> @guillaumeguy hey Guillaume! thanks for reporting this!
> 
> could you try the latest version and see if it resolves it on your end?

**Comment by lucidrains** [comment]
@guillaumeguy think you can figure it out from that error message?

**Comment by lucidrains** [comment]
@guillaumeguy i'll give you some time to figure it out, it'll be educational even if you are a software engineer dabbling with deep learning
