### ISSUE TITLE
Bug in ff_glu  (Encoder(..., ff_glu=True))

### ISSUE THREAD

**Issue by Froskekongen** [lucidrains/x-transformers#94]
In the current released version of x-transformer (x-transformers-0.29.1), there seems to be a bug when enabling ff_glu (it also happens if enabling ff_swish).

To reproduce:
```
from x_transformers import Encoder
import torch

base_enc = Encoder(dim=64, depth=6, heads=8, ff_glu=True)
dt = torch.randn(10, 120, 64)
base_out = base_enc(dt)
```
Output:

```
Traceback (most recent call last):
  File "/home/erlenda/repos/universal_ts_representation/tsuniv/backbones/config.py", line 66, in <module>
    base_out = base_enc(dt)
  File "/home/erlenda/.conda/envs/tsuniv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/erlenda/.conda/envs/tsuniv/lib/python3.10/site-packages/x_transformers/x_transformers.py", line 952, in forward
    out = block(x)
  File "/home/erlenda/.conda/envs/tsuniv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/erlenda/.conda/envs/tsuniv/lib/python3.10/site-packages/x_transformers/x_transformers.py", line 486, in forward
    return self.net(x)
  File "/home/erlenda/.conda/envs/tsuniv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/erlenda/.conda/envs/tsuniv/lib/python3.10/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/erlenda/.conda/envs/tsuniv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/erlenda/.conda/envs/tsuniv/lib/python3.10/site-packages/x_transformers/x_transformers.py", line 440, in forward
    x, gate = self.proj(x).chunk(2, dim = -1)
  File "/home/erlenda/.conda/envs/tsuniv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/erlenda/.conda/envs/tsuniv/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1200x256 and 64x512)
```

**Comment by Froskekongen** [comment]
Thanks, @lucidrains! It seems to be fixed now.
